#Author: KangLin(kl222@126.com)

sudo: required
dist: trusty

language: cpp

cache:
  - apt: true
  - directories:
    - Tools

compiler:
  - g++

jdk: oraclejdk7

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com

env:
  matrix:
    - BUILD_TARGERT="linux" QT_VERSION_DIR=5.13 QT_VERSION=5.13.0
    - BUILD_TARGERT="android_armv7" QT_VERSION_DIR=5.13 QT_VERSION=5.13.0
    - BUILD_TARGERT="linux" QT_VERSION_DIR=5.12 QT_VERSION=5.12.4
    - BUILD_TARGERT="android_armv7" QT_VERSION_DIR=5.12 QT_VERSION=5.12.4
    - BUILD_TARGERT="linux" QT_VERSION_DIR=5.9 QT_VERSION=5.9.8
    - BUILD_TARGERT="android_armv7" QT_VERSION_DIR=5.9 QT_VERSION=5.9.8

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
install:
  - echo "Starting installation..."
  - bash ${TRAVIS_BUILD_DIR}/ci/build-install-tools.sh #> /dev/null
  - echo "Finished installation."

before_script:
  - echo "Starting before_script..."
  - source ${TRAVIS_BUILD_DIR}/ci/build_env.sh
  - echo "Finished before_script."

script:
  - echo "Starting script..."
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - ${QT_ROOT}/bin/qmake -o Makefile CONFIG+=Release ${TRAVIS_BUILD_DIR}/src/QZXing.pro
  - make -f Makefile
  - echo "Finished script."
